/**
 * Parser for rsync `--info=stats2` output. Every rsync child runs under
 * LC_ALL=C (exec/'s minimal env), so the labels are stable English and the
 * numbers use comma thousands-grouping - the parser strips commas and nothing
 * else. Pure string work; the caller decides what a null (unparsable) means.
 */

/** The numbers backupkit consumes from one stats2 block. */
export interface RsyncStats {
    /** "Number of regular files transferred". */
    filesTransferred: number;
    /** "Number of files" (all types, both sides' file list). */
    totalFiles: number;
    /**
     * "Total transferred file size" in bytes - the real delta. From an
     * estimate (--dry-run) pass this is `deltaBytes` for the disk guard; from
     * the transfer pass it is the report's `bytesTransferred`.
     */
    totalTransferredSize: number;
}

/**
 * Extract the integer following `<label>:` on its own stats line. Tolerates
 * comma grouping and trailing text ("bytes", "(reg: ..., dir: ...)"). Returns
 * null when the label is absent or its value is not a safe integer.
 *
 * The LAST match wins, not the first: rsync relays messages generated by the
 * REMOTE onto the local client's stdout, ahead of the client's own stats block,
 * so a compromised source that prints a stats-shaped block picked every number
 * backupkit acts on - `Total transferred file size: 0` walked the disk guard
 * past a full filesystem, and an inflated `Number of files` silenced the
 * content-collapse tripwire (invariant 27), the only content signal protecting
 * the archive. The client's own block is always printed last.
 *
 * The bound is `Number.isSafeInteger`, not `Number.isFinite`: a 400-digit run
 * of digits parses to Infinity, and an infinite delta or file count makes every
 * threshold comparison downstream vacuously true (same reasoning as the remote
 * store's `df` parser).
 */
function statValue(output: string, label: string): number | null {
    const pattern = new RegExp(`^${label}:\\s+([0-9][0-9,]*)`, "gm");
    const last = [...output.matchAll(pattern)].at(-1);
    if (last === undefined) {
        return null;
    }
    const value = Number(last[1].replaceAll(",", ""));
    return Number.isSafeInteger(value) ? value : null;
}

/**
 * Parse one rsync --info=stats2 output block. Returns null when any required
 * line is missing (truncated output, wrong locale, not a stats block).
 */
export function parseStats2(output: string): RsyncStats | null {
    const filesTransferred = statValue(output, "Number of regular files transferred");
    const totalFiles = statValue(output, "Number of files");
    const totalTransferredSize = statValue(output, "Total transferred file size");
    if (filesTransferred === null || totalFiles === null || totalTransferredSize === null) {
        return null;
    }
    return { filesTransferred, totalFiles, totalTransferredSize };
}
